# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_differentiate <- function(Coeffs, Degrees, DWR) {
    .Call(`_mpolynom_rcpp_differentiate`, Coeffs, Degrees, DWR)
}

rcpp_evaluate <- function(Coeffs, Degrees, Values) {
    .Call(`_mpolynom_rcpp_evaluate`, Coeffs, Degrees, Values)
}

